services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - CLIENT_GITHUB_ID=${CLIENT_GITHUB_ID}
      - CLIENT_GITHUB_SECRET=${CLIENT_GITHUB_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME=${NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME}
      - NEXT_PUBLIC_PUSHER_APP_KEY=${NEXT_PUBLIC_PUSHER_APP_KEY}
      - PUSHER_APP_ID=${PUSHER_APP_ID}
      - PUSHER_SECRET=${PUSHER_SECRET}
    volumes:
      - .:/app
    command: npm run dev
